//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmiIptvPlayer.i18n {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AmiIptvPlayer.i18n.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AmiIPTVPlayer is a simple iptv player using MVP library.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AboutUs....
        /// </summary>
        public static string AboutUsTitle {
            get {
                return ResourceManager.GetString("AboutUsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Can&apos;t obtain any account info result for your iptv url, please review it.
        /// </summary>
        public static string ACCOUNT_INFO_ERROR {
            get {
                return ResourceManager.GetString("ACCOUNT_INFO_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This is your account info:.
        /// </summary>
        public static string AccountInfoHead {
            get {
                return ResourceManager.GetString("AccountInfoHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account Info.
        /// </summary>
        public static string AccountInfoTitle {
            get {
                return ResourceManager.GetString("AccountInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Active connections:.
        /// </summary>
        public static string ActiveCons {
            get {
                return ResourceManager.GetString("ActiveCons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All.
        /// </summary>
        public static string ALLGROUP {
            get {
                return ResourceManager.GetString("ALLGROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        public static string AS_EN {
            get {
                return ResourceManager.GetString("AS_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a French.
        /// </summary>
        public static string AS_FR {
            get {
                return ResourceManager.GetString("AS_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a None.
        /// </summary>
        public static string AS_NONE {
            get {
                return ResourceManager.GetString("AS_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish.
        /// </summary>
        public static string AS_SP {
            get {
                return ResourceManager.GetString("AS_SP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Turkish.
        /// </summary>
        public static string AS_TR {
            get {
                return ResourceManager.GetString("AS_TR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unknown.
        /// </summary>
        public static string AS_UN {
            get {
                return ResourceManager.GetString("AS_UN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Credentials.
        /// </summary>
        public static string ASK_PASS {
            get {
                return ResourceManager.GetString("ASK_PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Block List.
        /// </summary>
        public static string BlockList {
            get {
                return ResourceManager.GetString("BlockList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Channel List.
        /// </summary>
        public static string ChannelList {
            get {
                return ResourceManager.GetString("ChannelList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clear.
        /// </summary>
        public static string CLEAR {
            get {
                return ResourceManager.GetString("CLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please load iptv list.
        /// </summary>
        public static string DEFAULT_MSG_NO_LIST {
            get {
                return ResourceManager.GetString("DEFAULT_MSG_NO_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Time: .
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New VOD&apos;s request.
        /// </summary>
        public static string EmailHeader {
            get {
                return ResourceManager.GetString("EmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hi this is a new request sended via AmiIptvPlayer app..
        /// </summary>
        public static string EmailText {
            get {
                return ResourceManager.GetString("EmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EPG Loaded:.
        /// </summary>
        public static string EPGloaded {
            get {
                return ResourceManager.GetString("EPGloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error processing EPG, please check your url.
        /// </summary>
        public static string ERROR_EPG {
            get {
                return ResourceManager.GetString("ERROR_EPG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exit.
        /// </summary>
        public static string ExitBtn {
            get {
                return ResourceManager.GetString("ExitBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expiration date:.
        /// </summary>
        public static string ExpirationDate {
            get {
                return ResourceManager.GetString("ExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File.
        /// </summary>
        public static string FileTool {
            get {
                return ResourceManager.GetString("FileTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must set a parental password in your settings before lock any channels..
        /// </summary>
        public static string FillParentalPass {
            get {
                return ResourceManager.GetString("FillParentalPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a For send new request you must set your provider iptv email request into settings.
        /// </summary>
        public static string FillReqEmail {
            get {
                return ResourceManager.GetString("FillReqEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please fill title and year before send request.
        /// </summary>
        public static string FillReqVOD {
            get {
                return ResourceManager.GetString("FillReqVOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filter.
        /// </summary>
        public static string FILTER {
            get {
                return ResourceManager.GetString("FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filter list:.
        /// </summary>
        public static string FilterList {
            get {
                return ResourceManager.GetString("FilterList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Original title.
        /// </summary>
        public static string FIOrigTitle {
            get {
                return ResourceManager.GetString("FIOrigTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Title.
        /// </summary>
        public static string FITitle {
            get {
                return ResourceManager.GetString("FITitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fix Identification.
        /// </summary>
        public static string FixIdentTitle {
            get {
                return ResourceManager.GetString("FixIdentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Year.
        /// </summary>
        public static string FIYear {
            get {
                return ResourceManager.GetString("FIYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Groups:.
        /// </summary>
        public static string GROUPS {
            get {
                return ResourceManager.GetString("GROUPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Help.
        /// </summary>
        public static string HELP {
            get {
                return ResourceManager.GetString("HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Catalan.
        /// </summary>
        public static string LangCAT {
            get {
                return ResourceManager.GetString("LangCAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        public static string LangEN {
            get {
                return ResourceManager.GetString("LangEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a French.
        /// </summary>
        public static string LangFR {
            get {
                return ResourceManager.GetString("LangFR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish (Spain).
        /// </summary>
        public static string LangSP {
            get {
                return ResourceManager.GetString("LangSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Default system language.
        /// </summary>
        public static string LangSYS {
            get {
                return ResourceManager.GetString("LangSYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Turkish.
        /// </summary>
        public static string LangTR {
            get {
                return ResourceManager.GetString("LangTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language:.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please set your parental control credentials.
        /// </summary>
        public static string lbAskPass {
            get {
                return ResourceManager.GetString("lbAskPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You set incorrect pass.
        /// </summary>
        public static string lbAskPassError {
            get {
                return ResourceManager.GetString("lbAskPassError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categories:.
        /// </summary>
        public static string lbCategoryTitle {
            get {
                return ResourceManager.GetString("lbCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Country.
        /// </summary>
        public static string lbCountryTitle {
            get {
                return ResourceManager.GetString("lbCountryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description.
        /// </summary>
        public static string lbDescriptionTitle {
            get {
                return ResourceManager.GetString("lbDescriptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EndTime:.
        /// </summary>
        public static string lbEndTimeTitle {
            get {
                return ResourceManager.GetString("lbEndTimeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Internationalization.
        /// </summary>
        public static string lbI18N {
            get {
                return ResourceManager.GetString("lbI18N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parental control password.
        /// </summary>
        public static string lbParentalControl {
            get {
                return ResourceManager.GetString("lbParentalControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ratings:.
        /// </summary>
        public static string lbRatingsTitle {
            get {
                return ResourceManager.GetString("lbRatingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Release Date:.
        /// </summary>
        public static string lbReleaseDateTitle {
            get {
                return ResourceManager.GetString("lbReleaseDateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email for VOD request:.
        /// </summary>
        public static string lbRequestEmail {
            get {
                return ResourceManager.GetString("lbRequestEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Default audio language:.
        /// </summary>
        public static string lbSettingsDefAud {
            get {
                return ResourceManager.GetString("lbSettingsDefAud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Default sub language:.
        /// </summary>
        public static string lbSettingsDefSub {
            get {
                return ResourceManager.GetString("lbSettingsDefSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a URL EPG:.
        /// </summary>
        public static string lbSettingsEPG {
            get {
                return ResourceManager.GetString("lbSettingsEPG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UI Language:.
        /// </summary>
        public static string lbSettingsUILang {
            get {
                return ResourceManager.GetString("lbSettingsUILang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a URL IPTV:.
        /// </summary>
        public static string lbSettingsURL {
            get {
                return ResourceManager.GetString("lbSettingsURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stars:.
        /// </summary>
        public static string lbStarsTitle {
            get {
                return ResourceManager.GetString("lbStarsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a StartTime:.
        /// </summary>
        public static string lbStartTimeTitle {
            get {
                return ResourceManager.GetString("lbStartTimeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Title.
        /// </summary>
        public static string lbTitleTitle {
            get {
                return ResourceManager.GetString("lbTitleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Years release:.
        /// </summary>
        public static string lbYearsTitle {
            get {
                return ResourceManager.GetString("lbYearsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loaded.
        /// </summary>
        public static string LOADED {
            get {
                return ResourceManager.GetString("LOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loading....
        /// </summary>
        public static string LOADING {
            get {
                return ResourceManager.GetString("LOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Laoding channels... please wait a moment.
        /// </summary>
        public static string LOADING_CHANNELS {
            get {
                return ResourceManager.GetString("LOADING_CHANNELS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show Description.
        /// </summary>
        public static string LongDescriptionTitle {
            get {
                return ResourceManager.GetString("LongDescriptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Max. connections:.
        /// </summary>
        public static string MaxCons {
            get {
                return ResourceManager.GetString("MaxCons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Click for more details.
        /// </summary>
        public static string MORE_DETAILS {
            get {
                return ResourceManager.GetString("MORE_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Movie.
        /// </summary>
        public static string Movie {
            get {
                return ResourceManager.GetString("Movie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Not found.
        /// </summary>
        public static string NOT_FOUND {
            get {
                return ResourceManager.GetString("NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Doesn&apos;t exists channel number: .
        /// </summary>
        public static string NOT_FOUND_CH {
            get {
                return ResourceManager.GetString("NOT_FOUND_CH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parental Control.
        /// </summary>
        public static string ParentalControl {
            get {
                return ResourceManager.GetString("ParentalControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Poster of VOD.
        /// </summary>
        public static string PosterEmail {
            get {
                return ResourceManager.GetString("PosterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AmiIPTVPlayer: Settings.
        /// </summary>
        public static string PreferencesTitle {
            get {
                return ResourceManager.GetString("PreferencesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quit.
        /// </summary>
        public static string QUIT {
            get {
                return ResourceManager.GetString("QUIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Refresh EPG list.
        /// </summary>
        public static string RefreshEPGTool {
            get {
                return ResourceManager.GetString("RefreshEPGTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Refresh IPTV list.
        /// </summary>
        public static string RefreshListTool {
            get {
                return ResourceManager.GetString("RefreshListTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Request new VOD.
        /// </summary>
        public static string RequestNewVOD {
            get {
                return ResourceManager.GetString("RequestNewVOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to resume the video?.
        /// </summary>
        public static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        public static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure save the current block list?.
        /// </summary>
        public static string SaveBlockList {
            get {
                return ResourceManager.GetString("SaveBlockList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search again.
        /// </summary>
        public static string SearchAgainBtn {
            get {
                return ResourceManager.GetString("SearchAgainBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search:.
        /// </summary>
        public static string SearchLb {
            get {
                return ResourceManager.GetString("SearchLb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mark as seen.
        /// </summary>
        public static string Seen {
            get {
                return ResourceManager.GetString("Seen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fill info manually.
        /// </summary>
        public static string SendExtra {
            get {
                return ResourceManager.GetString("SendExtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Server:.
        /// </summary>
        public static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AmiIptvPlayer: new request VOD.
        /// </summary>
        public static string SubjectEmail {
            get {
                return ResourceManager.GetString("SubjectEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subtitles:.
        /// </summary>
        public static string Subs {
            get {
                return ResourceManager.GetString("Subs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Thanks for using the app.
        /// </summary>
        public static string ThanksEmail {
            get {
                return ResourceManager.GetString("ThanksEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unknown.
        /// </summary>
        public static string UNKNOWN {
            get {
                return ResourceManager.GetString("UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clean resume position.
        /// </summary>
        public static string UnResume {
            get {
                return ResourceManager.GetString("UnResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mark as unseen.
        /// </summary>
        public static string UnSeen {
            get {
                return ResourceManager.GetString("UnSeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Get Track URL.
        /// </summary>
        public static string URLinfo {
            get {
                return ResourceManager.GetString("URLinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please copy that URL and set in your favourite player..
        /// </summary>
        public static string URLInfoFooter {
            get {
                return ResourceManager.GetString("URLInfoFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The URL for that track is:.
        /// </summary>
        public static string URLInfoHead {
            get {
                return ResourceManager.GetString("URLInfoHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Version:.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volume:.
        /// </summary>
        public static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Without group.
        /// </summary>
        public static string WOGROUP {
            get {
                return ResourceManager.GetString("WOGROUP", resourceCulture);
            }
        }
    }
}
